version: '3'
services:
  b8r-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - DB_URI=mongodb+srv://b8r:homes@cluster0.sbfwcs4.mongodb.net/b8r?retryWrites=true&w=majority
      - PORT=5000
    ports:
      - "5000:5000"
    volumes:
      - /app/node_modules
      - .:/app